#!/bin/bash

#PBS -N HPC
#PBS -q normal
#PBS -l select=1:ncpus=10:mem=40G
#PBS -l walltime=99:00:00
#PBS -P Personal
#PBS -j oe
#PBS -o ./hpc4.o
#PBS -e ./hpc4.e
# mail alert at (b)eginning, (e)nd and (a)bortion of execution
#PBS -m bea
# send mail to the following address
#PBS -M e0010911@u.nus.edu

echo hpc
pwd
cd $PBS_O_WORKDIR
module load anaconda/3
source activate tf_1.9
export PYTHONHOME=${HOME}/.conda/envs/tf_1.9
python hpc.py
