#!/bin/bash

#PBS -N hpc_pru_high
#PBS -q normal
#PBS -l select=1:ncpus=20:mem=80G
#PBS -l walltime=99:00:00
#PBS -P Personal
#PBS -j oe
#PBS -o ./hpc_pru_high.o
#PBS -e ./hpc_pru_high.e
# mail alert at (b)eginning, (e)nd and (a)bortion of execution
#PBS -m bea
# send mail to the following address
#PBS -M e0010911@u.nus.edu

echo hpc_pru_high
pwd
cd $PBS_O_WORKDIR
module load anaconda/3
source activate tf_1.9
export PYTHONHOME=${HOME}/.conda/envs/tf_1.9
python hpc_pru_high.py
