#!/bin/bash

#PBS -N hpc_tesla_low
#PBS -q normal
#PBS -l select=1:ncpus=20:mem=80G
#PBS -l walltime=99:00:00
#PBS -P Personal
#PBS -j oe
#PBS -o ./hpc_tesla_low.o
#PBS -e ./hpc_tesla_low.e
# mail alert at (b)eginning, (e)nd and (a)bortion of execution
#PBS -m bea
# send mail to the following address
#PBS -M e0010911@u.nus.edu

echo hpc_tesla_low
pwd
cd $PBS_O_WORKDIR
module load anaconda/3
source activate tf_1.9
export PYTHONHOME=${HOME}/.conda/envs/tf_1.9
python hpc_tesla_low.py
